import Link from "next/link";

import Header from "./components/Header/Header";
import Footer from "./components/Footer/Footer";

import "./globals.scss";

export const metadata = {
  title: "WR",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body>
        <main className="main">
          <Header />
          <div className="content">{children}</div>
          <Footer />
        </main>
        <div className="socials-wrapper">
          <ul>
            <li>
              <Link
                href="https://www.instagram.com/_tom_aster/"
                target="_blank"
              >
                <img src="/icons/insta-icon.svg" alt="" />
              </Link>
            </li>
            <li>
              <Link href="https://codepen.io/Weverton-Ribeiro" target="_blank">
                <img src="/icons/codepen-icon.svg" alt="" />
              </Link>
            </li>
            <li>
              <Link href="https://github.com/WevertonRibeiro" target="_blank">
                <img src="/icons/github-icon.svg" alt="" />
              </Link>
            </li>
            <li>
              <Link
                href="https://www.linkedin.com/in/weverton-ribeir0/"
                target="_blank"
              >
                <img src="/icons/linkedin-icon.svg" alt="" />
              </Link>
            </li>
          </ul>
        </div>
      </body>
    </html>
  );
}
